spring:
  datasource:
    url: jdbc:h2:file:./data/booktine;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    #jdbc:h2:file:./data/booktine;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    #jdbc:h2:mem:booktine;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
h2:
    console:
      enabled: true
      path: /h2-console